### ISSUE TITLE
Can't create trigger

### ISSUE THREAD

**Issue by usbulat** [moira-alert/web2.0#145] opened 2018-06-01 07:11 UTC
Hello,

v2.2.0-1
When first opening Moira in browser, trying to create trigger the "Loading" message is shown and nothing happens. I've found a workaround - to switch "Only problems" on and off on main page, this solves the problem, but only on one browser. If trying to create trigger on another browser, same problem appears.
![2ojvxu](https://user-images.githubusercontent.com/22560358/40826680-04a2e180-6584-11e8-8b5d-4df129071808.jpg)

**Comment by titusjaka** [comment] 2018-06-01 07:27
Hi @usbulat ,

I'll try to reproduce it by myself and let you know about the result.

**Comment by sashasushko** [comment] 2018-06-01 10:57
Hi @usbulat 
Please, tell me, when and how you get Moira distro? Because, we fixed same problem, but didn't release yet.

**Comment by kamaev** [comment] 2018-06-01 11:27
Hi! Yes, this was fixed in https://github.com/moira-alert/web2.0/commit/1e4bc8cb526cd2dd585d92bf16fdbfee9dee10dd
Will be released with tag 2.3

**Closed** 2018-06-01 11:30 UTC
Labels: WIP, bug
